### ISSUE TITLE
handleHttpException not logging errors properly

### ISSUE THREAD

**Issue by Acrontum-Carmichael** [acrontum/generate-it-typescript-server#115]
This file:
`src/http/nodegen/middleware/handleHttpException.ts`

It doesn't dump reject errors to the console properly, when the console err is lifted the err is console properly:
```
import * as express from 'express';
import { HttpException } from '../errors';
import { NodegenRequest } from '../interfaces';
import { createHttpExceptionFromErr } from '@/http/nodegen/utils/createHttpExceptionFromErr';
/**
 * Http Exception handler
 */
export default () => (err: any, req: NodegenRequest, res: express.Response, next: express.NextFunction) => {
  console.error(err);
  if (!(err instanceof HttpException)) {
    err = createHttpExceptionFromErr(err);
  }
  if (err.isJson()) {
    return res.status(err.status).json(err.body);
  } else {
    return res.status(err.status).send(err.body);
  }
};
```

**Comment by Acrontum-Carmichael** [comment]
https://github.com/acrontum/generate-it-typescript-server/blob/master/src/http/nodegen/middleware/handleHttpException.ts#L10

This was a complete blocker as errors were not reaching the logs in some cases; this is a temp fix which does not resolve the issue, but works around it.

**Comment by p-mcgowan** [comment]
IMO this issue is still open - would be great to find a more permanent and less verbose solution for proper error handling, what do you think?
