### ISSUE TITLE
Parse auth header a bit more uniformly

### ISSUE THREAD

**Issue by p-mcgowan** [acrontum/generate-it-typescript-server#117]
If you want JWT in a header other than `Authorization`, it's parse as apiKey.

Since the Authorization header is the only one which complies with `<type> <credentials>`, if you want to set `x-auth-token: <jwt>` then it does not parse into jwt but rather apikey.

This isn't really a problem, except for when changing from Authorization to any other header, or vice-versa, it means anywhere that relied on `req.jwt` or `req.apiKey` now needs to change - IMO, I don't see much benefit in splitting apiKey and JWT, but rather just use `req.auth` or something, and the only difference between `Authorization: Bearer <jwt>` and `x-auth-token: <jwt>` is that auth expects `Bearer` to precede the token. Not sure how / if this works with basic auth either

**Comment by johndcarmichael** [comment]
Yea the access service was intentionally kept out of the managed layer as it is too complex to solve for every situation.

I think it should be expected that the developer write in their own logic.

**Comment by p-mcgowan** [comment]
makes sense
