### ISSUE TITLE
[ENH] add more http handlers, or a generic http error factory

### ISSUE THREAD

**Issue by p-mcgowan** [acrontum/generate-it-typescript-server#32]
For instance, with MS arch we often need a way to inform the client that an error occured from a remote service - in this case, a 503 would do that. 

Right now, most unhandled http errors are just propagated as 500's, which realistically should never happen and should indicate an urgent, unhandled, and unexpected error occcured.

Instead of adding handlers for each type, we could refactor custom-errors into an HttpError class, with a status code.

This would also make refactoring other errors (eg joi, db validation errors) into a more consumable error schema much easier

**Comment by Acrontum-Carmichael** [comment]
there is this one in there at the moment: src/http/nodegen/middleware/handleStatusMessageErrors.ts

it is just not included into the by default: src/http/middlewareErrorHandling.ts

**Comment by p-mcgowan** [comment]
ah, i see that now.

Interesting - it wasn't in some other projects. Maybe I didn't update.

It's a good stop-gap - I suppose if you only even want to send errors in the form of `{ message: string }` it works, but I think there is a much simpler solution that would handle all status codes.

**Comment by p-mcgowan** [comment]
Basically, something like this
```typescript
// export const { HttpStatusMessageEnum } = { 200: 'OK', 500: 'Internal Server Error', ... etc }
import { HttpStatusMessages } from './status-messages';

class HttpException extends Error {
  public status: number;
  public body: string | Record<string, any>;

  constructor(status: number, body?: string | Record<string, any>) {
    super();
    this.status = status;
    this.message = HttpStatusMessages[status];
    this.body = body;
  
    // https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work
    Object.setPrototypeOf(this, HttpException.prototype);
  }

  isJson() {
    return typeof this.body !== 'string';
  }
}

// could even build out some helper classes
class NotFoundException extends HttpException {
  constructor(message?: string | { [key: string]: any }) {
    super(404, message);
  }
}

// ...

// another_file.ts

import { NotFoundException } from '@/nodegen/errors/';

if (thing_was_not_found) {
  throw new NotFoundException(`I coulnd't find that for you...`);
}


// some_other_file.ts
import { HttpException } from '@/nodegen/errors/';

if (want_to_send_custom_http_error) {
  throw new HttpException(418, {
    message: 'Cannot brew coffee',
    errors: [{ message: 'Unable to complete request', reason: 'I am a teapot' }],
  });
}


// then middleware becomes much easier:
// handleHttpException.ts
import * as express from 'express';
import NodegenRequest from '@/nodegen'

/**
 * Http Exception handler
 */
export const httpExceptionHandler = (err: any, req: NodegenRequest, res: express.Response, next: express.NextFunction) => {
  if (err instanceof HttpException) {
    console.debug(err.stack);

    if (err.isJson()) {
      return res.status(err.status).json(err.body);
    } else {
      return res.status(err.status).send(err.message);
    }
  }

  next(err);
}
```

**Comment by Acrontum-Carmichael** [comment]
That looks awesome!

I wonder if this could be used as a proxy for the existing errors so this could be released without breaking existing code but also allowing you to do thing like:


```
// in some domain
if (noCoffee) {
  throw http418('Earl grey')
}
```

or from an actual use case: https://github.com/acrontum/openapi-nodegen-typescript-server/blob/master/src/http/nodegen/errors/406.ts

```
    if (!item) {
      throw http404('No item found by that id');
    }
```

**Comment by p-mcgowan** [comment]
i was just thinking the same thing - we could deprecate the old exports but leave them in for now.

already started working on it.

**Comment by p-mcgowan** [comment]
so ita not 100% backwards compatible - if you manually throw errors, you will need to add `throw new` instead of just `throw egal`, but at that point you might as well update to the new ones.

this should pave the way to a custom, default server reponse, and maybe we can get joi to format its errors instead of the other way around

**Comment by Acrontum-Carmichael** [comment]
however.. i broke something else in testing it:
```
0|ms-notification  | #
0|ms-notification  | # Fatal process OOM in New space setup
0|ms-notification  | #
0|ms-notification  | FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
0|ms-notification  | <--- Last few GCs --->
0|ms-notification  | <--- JS stacktrace --->
```

but it is pizza time so will take another look later
