### ISSUE TITLE
[FEAT] return app with http() setup

### ISSUE THREAD

**Issue by p-mcgowan** [acrontum/generate-it-typescript-server#56]
In either app.ts or server.ts, if we want to manually configure the express app, we can't (unless it's the config for the 2 middleware handlers).

Http should expose the created express app for additional configuration

This would allow custom listen callbacks as well (ie `app.listen(port, () => do something after successful start)`)

**Comment by Acrontum-Carmichael** [comment]
partially resolved in https://github.com/acrontum/generate-it-typescript-server/pulls
