### ISSUE TITLE
The asyncValidationMiddleware.ts has a bug that causes "unhandledPromiseRejection" error

### ISSUE THREAD

**Issue by SergiAcrontum** [acrontum/generate-it-typescript-server#76]
The bug is on line 32 `throw next(e)` should just be `return next(e)` or simply `next(e)`.

**Comment by Acrontum-Carmichael** [comment]
PR welcome ;)

**Comment by p-mcgowan** [comment]
working on it :) - good catch

**Comment by SergiAcrontum** [comment]
@p-mcgowan I added a PR already

**Comment by p-mcgowan** [comment]
my bad - please link the issue (either with `closes #76` in a commit, or in the PR it'self

**Comment by SergiAcrontum** [comment]
@p-mcgowan yep, forgot the damn #
