### ISSUE TITLE
queryArrayParserMiddleware is not intuitive or makes much sense

### ISSUE THREAD

**Issue by SergiAcrontum** [acrontum/generate-it-typescript-server#97]
From the express documentation (https://expressjs.com/en/5x/api.html#app.settings.table), it uses _qs_ library by default to parse queries.
Optionally, one can pass a parsing function if one really wants to declare an array using "," instead of the _qs_ way (which seems to be what the queryArrayParserMiddleware is doing). 

I dont think that we should enforce this convention to anyone using generate-it-server, as a query like
`?search="a day, in the morning"`
will get parsed to multiple queries.

**Comment by SergiAcrontum** [comment]
@johndcarmichael I would like to remove queryArrayParser from the default middlewares, but keep the file there, and if someone needs to parse comma separated values to arrays for for backwards compatibility, they can just pass it in the "preRouteApplicationRequestHandlers". Opinion?

**Comment by p-mcgowan** [comment]
I agree - it's not standard to parse commas in a qs by splitting, but if that's a feature used by people, it makes sense to have a config for that.
@SergiAcrontum  if you make a PR with some tests, if it looks good and (probably) won't break too much, we can likely merge it in

**Comment by Acrontum-Carmichael** [comment]
This feels like a recurring topic :D

My opinion is still the same. This was introduced by a dev who was building frontend api consumers using the java swagger code gen but consuming an api developed by generate-it. I personally have no use case for this middleware, but if it is completely removed it will break things.. so leaving it in and permitted the dev to inject the middleware into the http layer seems good to me.
